### ISSUE TITLE
what's the difference between local and global attention maps

### ISSUE THREAD

**Issue by voyager0003** [taki0112/UGATIT#106]
Thanks for great work! pytorch version is really readable
after reading the paper, I confused what's the difference between local and global attention maps?
Anyone can help me

**Comment by gdwei** [comment]
The numbers of conv layers are different, resulting in different perception field.&nbsp;



---Original---

**Comment by vegetable09** [comment]
@gdwei Thanks! your answer is short but very clear, just like Rick ^_^

**Comment by voyager0003** [comment]
@gdwei Thanks! your answer is short but very clear, just like Rick ^_^
