### ISSUE TITLE
Pre-trained model provided on googl drive looks broken

### ISSUE THREAD

**Issue by gyupro** [taki0112/UGATIT#118]
Hi,

I was trying to extract zip files that uploaded on Google Drive that you provided

They assume to be broken URLS as it says **error: invalid zip file with overlapped components (possible zip bomb)**

I tried both of URLS and they do not work.

**Comment by CambridgeComputing** [comment]
Try using 7zip. I was unable to open it as well in Windows with the built-in extractor, but 7zip opened it no problem.
