### ISSUE TITLE
OOM happens, tensorflow-gpu, freeMemory: 3.31GiB

### ISSUE THREAD

**Issue by kicGit** [taki0112/UGATIT#12]
how much memory need for trainning model by tensorflow-gpu?

**Comment by d0minikt** [comment]
Same "`Resource Exhausted`" issue shows up for me. Running on CPU is fine, but when switching to my GTX 970 I'm getting OOM on the default batch size of 1. How much memory is needed to train? Is there any way of reducing that?

**Comment by taki0112** [comment]
we used a v100 32GB GPU.

**Comment by wangshisheng** [comment]
I also get the OOM issue. Mine is 4GB GPU, well it is not enough~~
