### ISSUE TITLE
The course of true love never did run smooth

### ISSUE THREAD

**Issue by opentld** [taki0112/UGATIT#14]
I just want to ask, at this speed, can I see the end of training in my lifetime?

![image](https://user-images.githubusercontent.com/21096515/62531744-9b6ff180-b875-11e9-883b-31395fea530a.png)

Waiting for the pretrained model is wise for me, maybe...    @taki0112

**Comment by hitechbeijing** [comment]
Please turn down Iteration, Epoch and Batchsize

**Comment by 1mpossibleHacker** [comment]
Can you please tell me how did you train it? I cant train it.

**Comment by hitechbeijing** [comment]
I have not get the best result yet

**Comment by opentld** [comment]
@hitechbeijing
> Please turn down Iteration, Epoch and Batchsize

I'm using the default setting, epoch=100,iteration=10000,batch_size=1

p.s. 1 year is too long to me...

**Comment by hitechbeijing** [comment]
> @hitechbeijing
> 
> > Please turn down Iteration, Epoch and Batchsize
> 
> I'm using the default setting, epoch=100,iteration=10000,batch_size=1
> 
> p.s. 1 year is too long to me...

try epoch=10,iteration=1000,batch_size=1

**Comment by tafseerahmed** [comment]
What datasets are you using?

**Comment by hitechbeijing** [comment]
> What datasets are you using?

selife2anime

**Comment by tafseerahmed** [comment]
Could you link that?

**Comment by sdy0803** [comment]
@hitechbeijing hi, could you link the database u r using?

**Comment by sdy0803** [comment]
@hitechbeijing hi, could you link the database u r using?

**Comment by hitechbeijing** [comment]
I have tested the NVIDIA Tesla V100, it just 4 times faster than desktop CPU. and as faster as intel Xeon gold CPU.

**Comment by tafseerahmed** [comment]
Cool but could you upload and link the dataset you're using

**Comment by hitechbeijing** [comment]
> Cool but could you upload and link the dataset you're using

see  #6

**Comment by HLearning** [comment]
2080ti： each epoch takes 2 hours

**Comment by hitechbeijing** [comment]
> 2080ti： each epoch takes 2 hours

increase batchsize?

**Comment by HLearning** [comment]
> > 2080ti： each epoch takes 2 hours
> 
> increase batchsize?
light=True， epoch=100， iteration=10000， batch_size=1

**Comment by hitechbeijing** [comment]
> > > 2080ti： each epoch takes 2 hours
> > 
> > 
> > increase batchsize?
> > light=True， epoch=100， iteration=10000， batch_size=1

am not turn on light. I think it is the reason for slow.

**Comment by taki0112** [comment]
1. We released [**50 epoch**](https://drive.google.com/file/d/1V6GbSItG3HZKv3quYs7AP0rr1kOCT3QO/view) and [**100 epoch**](https://drive.google.com/file/d/19xQK2onIy-3S5W5K-XIh85pAg_RNvBVf/view) checkpoints so that people could test more widely.

2. Also, We published [**the selfie2anime datasets**](https://drive.google.com/file/d/1xOWj1UVgp6NKMT3HbPhBbtq2A4EDkghF/view) we used in the paper.

3. And, we fixed [code in **smoothing**](https://github.com/taki0112/UGATIT/blob/master/ops.py#L196)

4. In the test image, I recommend that your face be in the **center**.
