### ISSUE TITLE
TypeError: Input 'filename' of 'ReadFile' Op has type float32 that does not match expected type of string.

### ISSUE THREAD

**Issue by 1mpossibleHacker** [taki0112/UGATIT#15]
I was looking forwards to train it and this error popped up.

**Comment by d0minikt** [comment]
@1mpossibleHacker make sure your dataset is located in the `./dataset` folder and pass its name with the `--dataset` argument. [Here is an example of a dataset](https://github.com/znxlwm/UGATIT-pytorch/tree/master/dataset/).

**Comment by 1mpossibleHacker** [comment]
> @1mpossibleHacker make sure your dataset is located in the `./dataset` folder and pass its name with the `--dataset` argument. [Here is an example of a dataset](https://github.com/znxlwm/UGATIT-pytorch/tree/master/dataset/).

how long does it take to train?

**Comment by taki0112** [comment]
@1mpossibleHacker 
one v100 32GB GPU, 4 days
