### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by Alpaca4610** [taki0112/UGATIT#24]
_> WARNING:tensorflow:From C:\Users\Lenovo\Desktop\UGATIT-master\UGATIT.py:355: shuffle_and_repeat (from tensorflow.contrib.data.python.ops.shuffle_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.experimental.shuffle_and_repeat(...)`.
WARNING:tensorflow:From C:\Users\Lenovo\Desktop\UGATIT-master\UGATIT.py:355: map_and_batch (from tensorflow.contrib.data.python.ops.batching) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.experimental.map_and_batch(...)`.
WARNING:tensorflow:From C:\Users\Lenovo\Desktop\UGATIT-master\UGATIT.py:355: prefetch_to_device (from tensorflow.contrib.data.python.ops.prefetching_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.experimental.prefetch_to_device(...)`.

ValueError: Tensor conversion requested dtype string for Tensor with dtype float32: 'Tensor("arg0:0", shape=(), dtype=float32)'

TypeError: Input 'filename' of 'ReadFile' Op has type float32 that does not match expected type of string._

![image](https://user-images.githubusercontent.com/16055526/62611827-eb63bc80-b938-11e9-9f08-a7d89787ca86.png)

**Comment by 1mpossibleHacker** [comment]
Pretty much the same

**Comment by tafseerahmed** [comment]
Probably need @taki0112 to give requirements.txt and environment details.

**Comment by taki0112** [comment]
make sure your dataset is located in the `./dataset` folder and pass its name with the `--dataset` argument. [Here is an example of a dataset](https://github.com/znxlwm/UGATIT-pytorch/tree/master/dataset/).
