### ISSUE TITLE
I have a checkpoint but ugatit cant find it

### ISSUE THREAD

**Issue by 1mpossibleHacker** [taki0112/UGATIT#26]
wtf

**Comment by taki0112** [comment]
What path did you put the checkpoint file in?

**Comment by 1mpossibleHacker** [comment]
UGATIT's path : /mnt/d/UGATIT
checkpoint's path : /mnt/d/UGATIT/checkpoint
(checkpoint folder was automatically created)

**Comment by taki0112** [comment]
Did you train U-GAT-IT ?

**Comment by 1mpossibleHacker** [comment]
I got this error while training it

**Comment by taki0112** [comment]
@1mpossibleHacker 
what is the error message ?

**Comment by 1mpossibleHacker** [comment]
Searching for checkpoint
couldnt find a checkpoint
load failed
(this is not exactly what it said but you understood)

**Comment by taki0112** [comment]
`load failed` is not **error**...

Wait for training. Then it works.

**Comment by 1mpossibleHacker** [comment]
dude but what about the checkpoint. please reopen it i need answers

**Comment by taki0112** [comment]
@1mpossibleHacker 
When trained, checkpoints are automatically saved for every `save_freq` iterations.

https://github.com/taki0112/UGATIT/blob/master/main.py#L18

**Comment by 1mpossibleHacker** [comment]
it doesnt countinue after saying load failed. so i cant train

**Comment by LeonNerd** [comment]
iget a trouble "Load FAILURE"  i have some models andI've put it in the folder
Why does it appear?  Do I need to change the model path?
