### ISSUE TITLE
What GPU was it trained on?

### ISSUE THREAD

**Issue by hexicle** [taki0112/UGATIT#3]
I am training it on an NVIDIA Tesla K80 but it runs out of memory even when I put the `--light True` parameter.

**Comment by taki0112** [comment]
NVIDIA V100 32GB GPU.
It takes 4 days.

**Comment by hexicle** [comment]
Thank you, I ran out of memory because the process was running and I needed to reboot the server to free up the memory. It is not a recurring problem.

**Comment by FantasyJXF** [comment]
> One NVIDIA V100 32GB GPU.
> It takes 4 days.

Hello, did you train with `light`?
