### ISSUE TITLE
Add support for MacOS?

### ISSUE THREAD

**Issue by sfoley-gpqa** [taki0112/UGATIT#30]
After installing tensorflow and running 

python3 main.py --dataset selfie2anime

I'm getting the following error on MacOS (10.14.5)

TypeError: Input 'filename' of 'ReadFile' Op has type float32 that does not match expected type of string.

**Comment by wangshisheng** [comment]
I think this error may be not caused by OS, I use Windows 7, it gives me the same error...

**Comment by heart4lor** [comment]
selfie2anime dataset doesn't included in this repo currently, see #6 , your error may caused by this.

**Comment by taki0112** [comment]
It also works on MacOS.
But without the gpu, it would be slow.
