### ISSUE TITLE
Do you have a TPU version?

### ISSUE THREAD

**Issue by thewaifuai** [taki0112/UGATIT#31]
I am actively working on building a TPU version of UGATIT. By any chance do you already have or plan to work on a TPU implementation? The benefit is that (hopefully) instead of taking days it would take hours to train.

**Comment by sebasfavaron** [comment]
Dont have a TPU, but looking forward to people using this and sharing pretrained weights, lol. Keep at it!

**Comment by tafseerahmed** [comment]
> I am actively working on building a TPU version of UGATIT. By any chance do you already have or plan to work on a TPU implementation? The benefit is that (hopefully) instead of taking days it would take hours to train.

How about use PyTorch Lightning to make a multi GPU training Version.
