### ISSUE TITLE
The size of ckpt is 7.5G?

### ISSUE THREAD

**Issue by cumtwb** [taki0112/UGATIT#32]
I trained the network on my own dataset. But the size of saved checkpoint is 7.5G. Would you like to tell how much space your checkpoint occupies?

**Comment by heart4lor** [comment]
in my case one single ckpt occupies ~1.5G, but I set --light parameter to true because of poor GPU memory.

**Comment by HLearning** [comment]
in my case one single ckpt occupies ~1.6G, but I set --light parameter to true because of poor GPU memory.

**Comment by thewaifuai** [comment]
Using the light parameter my checkpoints were about 1.5G each.

**Comment by cumtwb** [comment]
Thank you! But I still have two problem:
1. Why the checkpoint of UGATIT is so huge? The ckpt of MUNIT is 100~150M, of CycleGAN is only ~40M.
2. The unique difference of setting the --light parameter to true or false is in the MLP function of AdaLIN. If --light==true, global average pooling will be used to input x. The output unit number of next fc layer is 64 * 4(ch * n_res)=256. 
light        false                        true
x       64 * 64 * 256           --> 256
fc      64 * 64 * 256 * 256 -->  256 * 64
A float32 parameter occupies 4B, all parameters of one full fc layer occupy 64 *64 * 256 * 256 * 4B = 1G. Therefore, the full a2b and b2a generators should occupy ~2G than the light generators. But my full ckpt occupies  ~7.5G, is 6G than your light ckpt. Why?
@heart4lor @HLearning @thewaifuai

**Comment by alcaster** [comment]
Original checkpoint(not light model) size is 7.5G
