### ISSUE TITLE
Crappy results

### ISSUE THREAD

**Issue by 1mpossibleHacker** [taki0112/UGATIT#38]
what are these results

**Comment by taki0112** [comment]
Show me what you saw.

**Comment by 1mpossibleHacker** [comment]
In the first try it just deepfried the photo and in the second try it blured it. It does nothing else than ruining photos

**Comment by tafseerahmed** [comment]
> In the first try it just deepfried the photo and in the second try it blured it. It does nothing else than ruining photos

Well, can you show your results and give more details as to how you arrived at that instead of just lambasting at the results? Doesn't help anyone.

**Comment by tafseerahmed** [comment]
> Show me what you saw.

![image](https://user-images.githubusercontent.com/12884292/62824437-44845800-bba6-11e9-8320-4f4e90919385.png)
Hey, I am training the full model on 4 x 2080 Ti's and the dataset is and everything else is same as yours with a minor difference 4k trainA, 4k train B, 100 testA and 100 testB. For how many epochs will I have to train?

**Comment by taki0112** [comment]
@tafseerahmed 
1. For how many epochs will I have to train?
I recommend a 50 or 100 epoch
2. the Generator loss is way higher than discriminator is that normal?
Yes, because `cam_weight` is high.
