### ISSUE TITLE
How to train on multi GPU?

### ISSUE THREAD

**Issue by creke** [taki0112/UGATIT#39]
Hi ,
I'm new to tensorflow, and I trained the model on a multi GPU server.
But it took only ONE gpu.
I want to make all of my gpus useful, is there a way to do so?
Thank you.

**Comment by kicGit** [comment]
me too

**Comment by tafseerahmed** [comment]
I am working on a PyTorch multi GPU-training version using Pytorch-lightning

**Comment by taki0112** [comment]
We didn't implement it in multi-gpu.
I think you'll need a little code change to do that.

**Comment by zhangyunming** [comment]
how to change the code if we use multi-gpus
it only can train light version on 11G memoy card
