### ISSUE TITLE
Error "Failed to find a checkpoint" 

### ISSUE THREAD

**Issue by davids91** [taki0112/UGATIT#4]
Hi, fiorst of all thank you for this awesome Net! 
 I was aiming to try it out, but got the error in the log: 
 ````
 [*] Reading checkpoints...
 [*] Failed to find a checkpoint
 [!] Load failed...
 [*] Test finished! 
````

the usage was the following:  `  python main.py --sample_dir customfolder --phase test --light true ` 
where I put a folder next to the source code inside the repository. Inside the folder there was only an image `02.png` on which I tried to  test the net on. 

I have tried absolute path as well,  but with the same error. Would you kindly show an example usage for only one picture, or folder? 
Thank you in advance!

**Comment by Wizwizard** [comment]
I have this problem too.

**Comment by shellpan** [comment]
you must train it first, only after that you can have a checkpoint to load

**Comment by taki0112** [comment]
`load failed` means that the checkpoint could not be called.
That is, you must train the U-GAT-IT model first.

**Comment by ElecRex** [comment]
I have the same problem, but I've already trained it.
When input the following command: ```python main.py --phrase test ```
The output is:
```
##### Information #####
# light :  True
# dataset :  selﬁe2anime
# batch_size :  1
# iteration per epoch :  1000

##### Generator #####
# residual blocks :  4

##### Discriminator #####
# discriminator layer :  6

##### Weight #####
# adv_weight :  1
# cycle_weight :  10
# identity_weight :  10
# cam_weight :  1000
 [*] Load FAILURE
 [*] Test finished!
```

**Comment by 1mpossibleHacker** [comment]
I had the same problem while training
