### ISSUE TITLE
"tf.errors.InvalidArgumentError" Occured while running with "--ch 16 --img_size 64"

### ISSUE THREAD

**Issue by FutaAlice** [taki0112/UGATIT#40]
Everything works well with default arguments, but training time seems too long on my GPU.

I attempted to use `"--ch 16 --img_size 64 --"` arguments and create a smaller model, but error occured while building model.

Any ideas about create a tiny model? Thanks a lot.

**Comment by taki0112** [comment]
If the image size is too small, It will be error in discriminator. 
I recommend not to reduce.
