### ISSUE TITLE
What does parameter 'sn' mean in function fully_connected_with_w?

### ISSUE THREAD

**Issue by zjuzxd94** [taki0112/UGATIT#46]
In the file ops.py, the prototype of function fully_connected_with_w is defined as:
`def fully_connected_with_w(x, use_bias=True, sn=False, reuse=False, scope='linear')`
what is the purpose of parameter 'sn' here?

**Comment by taki0112** [comment]
for `spectral_norm`
https://github.com/taki0112/UGATIT/blob/master/ops.py#L68
