### ISSUE TITLE
This topic is so HOT! Files cannot be downloaded~~

### ISSUE THREAD

**Issue by wangshisheng** [taki0112/UGATIT#49]
When I downloaded these two files that taki0112 shared, the google drive tells me this:

_Sorry, you are currently unable to view or download this file.
Too many users have recently viewed or downloaded this file. Try accessing this file again later. If the file you are trying to access is extremely large or Shared by many people, it can take up to 24 hours to view or download. If you are still unable to access the file after 24 hours, contact your domain administrator._

Could anyone share another link? Thanks a lot~~

**Comment by xizeyoupan** [comment]
see#5 latest

**Comment by Hezip** [comment]
me2

**Comment by abhinavdimri** [comment]
Workout this:
1. Add file to your drive
![Add File](https://user-images.githubusercontent.com/10084698/63105461-74fd3500-bf9e-11e9-91a8-4399cb9b44d0.png)

2. Right click on file and make copy
![Make-a-copy](https://user-images.githubusercontent.com/10084698/63105484-82b2ba80-bf9e-11e9-90ca-97315b46a517.jpg)

3. Download the file

![Download-min](https://user-images.githubusercontent.com/10084698/63105500-89413200-bf9e-11e9-9b80-49715d329fcf.jpg)

Hope it helps!
