### ISSUE TITLE
大佬们，我是小白，我下载了模型，应该不用下载数据集了吧？接下来该怎么处理自己的图片呢，望不吝指教谢谢啦

### ISSUE THREAD

**Issue by cqz-c** [taki0112/UGATIT#55]

**Comment by srauni** [comment]
1.将下载的模型放入checkpoint
![image](https://user-images.githubusercontent.com/40561902/63261056-1cd37500-c2b5-11e9-8f6f-72ea5f08ad9b.png)
2.若要照片转动漫，将其放入此文件夹
![image](https://user-images.githubusercontent.com/40561902/63261112-3a084380-c2b5-11e9-8826-2493f4fb675a.png)
3.若要动漫转照片，将其放入此文件夹
![image](https://user-images.githubusercontent.com/40561902/63261125-47253280-c2b5-11e9-99f5-5ba987c92d9c.png)
4.回到根目录，运行python main.py --dataset selfie2anime --phase test
5.在results查看运行结果
![image](https://user-images.githubusercontent.com/40561902/63261246-94a19f80-c2b5-11e9-9765-ea69856f2105.png)

**Comment by cqz-c** [comment]
谢谢啦么么哒

**Comment by calvin886** [comment]
> 1.将下载的模型放入checkpoint
> ![image](https://user-images.githubusercontent.com/40561902/63261056-1cd37500-c2b5-11e9-8f6f-72ea5f08ad9b.png)
> 2.若要照片转动漫，将其放入此文件夹
> ![image](https://user-images.githubusercontent.com/40561902/63261112-3a084380-c2b5-11e9-8826-2493f4fb675a.png)
> 3.若要动漫转照片，将其放入此文件夹
> ![image](https://user-images.githubusercontent.com/40561902/63261125-47253280-c2b5-11e9-99f5-5ba987c92d9c.png)
> 4.回到根目录，运行python main.py --dataset selfie2anime --phase test
> 5.在results查看运行结果
> ![image](https://user-images.githubusercontent.com/40561902/63261246-94a19f80-c2b5-11e9-9765-ea69856f2105.png)
您好， 您对这个模型的在测试的时候的参数量有做过估计吗
