### ISSUE TITLE
My test result is wrong.

### ISSUE THREAD

**Issue by 1160300806** [taki0112/UGATIT#56]
I download the pretrained model and test, but the result is like this ,what is the mistake,thank you!@taki0112 
![图片](https://user-images.githubusercontent.com/29518573/63249562-521f9900-c29c-11e9-803b-d9dd1904b044.png)

**Comment by BorisLestsov** [comment]
You probably did not load the model correctly. Providing the output log would certainly useful

**Comment by 1160300806** [comment]
i download the pretrained model and extract it, but some mistakes happened when extracting,it says UGATIT.model-1000000.meta was damaged and can not read the data in the compressed file UGATIT.model-1000000.data-00000-of-00001
![图片](https://user-images.githubusercontent.com/29518573/63258466-acc1f080-c2ae-11e9-8d13-052e226789f2.png)

**Comment by 1160300806** [comment]
> 
> 
> You probably did not load the model correctly. Providing the output log would certainly useful
i download the pretrained model and extract it, but some mistakes happened when extracting,it says UGATIT.model-1000000.meta was damaged and can not read the data in the compressed file UGATIT.model-1000000.data-00000-of-00001 
![图片](https://user-images.githubusercontent.com/29518573/63258685-31ad0a00-c2af-11e9-84fe-c718ce28c26a.png)

**Comment by BorisLestsov** [comment]
Yeah, you should look here https://github.com/taki0112/UGATIT/issues/50

**Comment by 1160300806** [comment]
> 
> 
> Yeah, you should look here #50

OK Thank you  very much.

**Comment by rehanpunjwani** [comment]
Can anybody guide me how to test the result's on my own image?
