### ISSUE TITLE
Failed to find a checkpoint...

### ISSUE THREAD

**Issue by zhangdanfeng888** [taki0112/UGATIT#58]
I download the pretrained model from baidu netdisk, this is my architecture
![image](https://user-images.githubusercontent.com/41187774/63395933-fa964000-c3f7-11e9-90ba-2563635b827f.png)
But when I test, the result is
![image](https://user-images.githubusercontent.com/41187774/63395961-10a40080-c3f8-11e9-9091-7f072fb402d0.png)
Please help me...This question puzzle me for 2 days.

**Comment by QQ2737499951** [comment]
Light is set to False, and if it is set to ture, the model must be retrained, and the default model cannot be imported. The default model is set to False 
===========
 light 设置为 False，如果设置为ture，必须重新训练模型，默认模型无法导入。 默认模型是设置为 False的
