### ISSUE TITLE
How to test on custom image?

### ISSUE THREAD

**Issue by ofirkris** [taki0112/UGATIT#61]
Using command: `python3 main.py --dataset selfie2anime --phase test`

Tried loading a sample image to "sample" folder, and I still get an empty index.html as result with the following html:
`<html><body><table><tr><th>name</th><th>input</th><th>output</th></tr>`

What am I doing wrong?

**Comment by Rejid** [comment]
Place the photo(s) you want to convert into UGATIT-master\dataset\selfie2anime\testA
