### ISSUE TITLE
Why trainA and trainB only have 3400 pictures?

### ISSUE THREAD

**Issue by GitHubZiqiangZhou** [taki0112/UGATIT#65]
UGATIT is great!
But I have some questions.
1.Why do you only use 3400 pictures in trainA and trainB?
2.if I use more pictures to train, for example 30000 trainA pictures and 30000 trainB pictures, need I change the iteration and epoch?
3.More trainA pictures is better, or more trainB pictures is better, or more trainA and trainB pictures is better?
You are the best!
Thank you!

**Comment by GitHubZiqiangZhou** [comment]
Anderson why don't you set iteration 3400 and epoch 300？

**Comment by GitHubZiqiangZhou** [comment]
And why don't you set iteration 3400 and epoch 300？

**Comment by taki0112** [comment]
1. I wanted to let you know that our model works well even though it's a small number
2. I don't know. I think epoch 100 is enough.
3. will be better
