### ISSUE TITLE
Why the pytorch version of UGATIT uses 4 discriminators?

### ISSUE THREAD

**Issue by zhanggd18** [taki0112/UGATIT#66]
""" Define Generator, Discriminator """
        self.genA2B = ResnetGenerator(input_nc=3, output_nc=3, ngf=self.ch, n_blocks=self.n_res, img_size=self.img_size, light=self.light).to(self.device)
        self.genB2A = ResnetGenerator(input_nc=3, output_nc=3, ngf=self.ch, n_blocks=self.n_res, img_size=self.img_size, light=self.light).to(self.device)
        self.disGA = Discriminator(input_nc=3, ndf=self.ch, n_layers=7).to(self.device)
        self.disGB = Discriminator(input_nc=3, ndf=self.ch, n_layers=7).to(self.device)
        self.disLA = Discriminator(input_nc=3, ndf=self.ch, n_layers=5).to(self.device)
        self.disLB = Discriminator(input_nc=3, ndf=self.ch, n_layers=5).to(self.device)
Can i discard the disLA and disLB?

**Comment by joashchn** [comment]
same question(Haven't read tf code yet)

**Comment by taki0112** [comment]
`disG` means a global discriminator
`disL` means  a local discriminator

we use 2 discriminator for each domain.
