### ISSUE TITLE
Extended tutorial

### ISSUE THREAD

**Issue by Romeorubiko** [taki0112/UGATIT#7]
It's an interesting work but people (like me) who doesn´t know about unsupervised networks could realy use an extended tutorial about how to run the commands (the flags mostly) and how to set up the folder hierarchy. And an exalmple would be nice too.

Using this comand:
`python--dataset dataset --phase test ` 

Keep having this output https://i.imgur.com/PRgQHVM.jpg

Thanks.

**Comment by taki0112** [comment]
Thank you. 
I'll write the Tutorial at README soon.
