### ISSUE TITLE
oom question

### ISSUE THREAD

**Issue by Jiaxin-Wen** [taki0112/UGATIT#82]
I've met the oom question with a TITAN xp 12GB GPU while running the original model(256px  , un-light mode)

How much memory would be enough to succefully run the code , like loading the 100-epoch pre-trained model?

**Comment by kmswlee** [comment]
i did it in 8G memory

**Comment by sooperset** [comment]
Inference is possible in 12GB, but training is not possible.

**Comment by swissalps9** [comment]
Try doing 128px, non-light. Works on 11GB
