### ISSUE TITLE
Pretrained weights

### ISSUE THREAD

**Issue by mojoee** [taki0112/UGATIT#88]
I just downloaded the pretrained weights and tried to extract them but it seems that they are damaged. Anyone else having the same issue?

**Comment by samarthsikand** [comment]
Yup, I faced the same issue while extracting them using WinRAR in Windows 10. But it was successfully extracted using 7zip. See comments in #72 .
![7zip](https://user-images.githubusercontent.com/16184715/81106781-ca65e180-8f33-11ea-9f06-092b1c0cc40d.JPG)

**Comment by mojoee** [comment]
okay thank you for the information. In the meanwhile I directly used the weights available from kaggle and unzipped from python script.
