### ISSUE TITLE
tensorflow version

### ISSUE THREAD

**Issue by shellpan** [taki0112/UGATIT#9]
Which version of tensorflow your code ran? I ran it under version 1.14.0, but it has some traceback.

**Comment by taki0112** [comment]
I used the TF 1.10.0

**Comment by chaowentao** [comment]
I used the TF 1.9.0

**Comment by QGB** [comment]
tf-gpu  1.13.0

**Comment by QGB** [comment]
pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.13.1-cp37-cp37m-linux_x86_64.whl
Collecting tensorflow-gpu==1.13.1 from https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.13.1-cp37-cp37m-linux_x86_64.whl
  Using cached https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.13.1-cp37-cp37m-linux_x86_64.whl
Collecting astor>=0.6.0 (from tensorflow-gpu==1.13.1)
  Using cached https://files.pythonhosted.org/packages/d1/4f/950dfae467b384fc96bc6469de25d832534f6b4441033c39f914efd13418/astor-0.8.0-py2.py3-none-any.whl
Collecting termcolor>=1.1.0 (from tensorflow-gpu==1.13.1)
  Downloading https://files.pythonhosted.org/packages/8a/48/a76be51647d0eb9f10e2a4511bf3ffb8cc1e6b14e9e4fab46173aa79f981/termcolor-1.1.0.tar.gz
Collecting grpcio>=1.8.6 (from tensorflow-gpu==1.13.1)
  ERROR: Could not find a version that satisfies the requirement grpcio>=1.8.6 (from tensorflow-gpu==1.13.1) (from versions: none)
ERROR: No matching distribution found for grpcio>=1.8.6 (from tensorflow-gpu==1.13.1)

**Comment by QGB** [comment]
`
/root/tf/UGATIT 11:26:54# python main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from UGATIT import UGATIT
  File "/root/tf/UGATIT/UGATIT.py", line 5, in <module>
    from tensorflow.contrib.data import prefetch_to_device, shuffle_and_repeat, map_and_batch
ImportError: cannot import name 'prefetch_to_device'
/root/tf/UGATIT 11:26:59# python -c 'import tensorflow as tf;print(tf.VERSION)'
1.6.0
`
