### ISSUE TITLE
I tried the train , but "Failed to find a checkpoint".

### ISSUE THREAD

**Issue by click-stack** [taki0112/UGATIT#97]
I tried the train using the test dataset , but "Failed to find a checkpoint". (in google colaboratory , tensorflow1.14.0)
How can I solve this problem?

`!python main.py --dataset train --phase train
`
...
 [*] Reading checkpoints...
 [*] Failed to find a checkpoint
 [!] Load failed...
^C
![result_images](https://user-images.githubusercontent.com/69844075/90500729-3dfbc980-e186-11ea-876f-d5c588997d92.png)

**Comment by Anku5hk** [comment]
Having same issue, i am getting 'Killed' after 'Load Failed' did you solved it ?

**Comment by Anku5hk** [comment]
Okay the fix is to set `--light True `.

**Comment by click-stack** [comment]
I tried the method you said and the learning went well!
Thank you!
